%%% This output was generated by embedproblem, version 1.7.7 (library version 1.8).
%%% Generated on Wed Mar 01 21:00:27 CET 2023
%%% using '$$dhol' embedding, version 1.0.
%%% Logic specification used:
%%% tff(dhol, logic, ($$dhol) == ([])).

thf(obj_type, type, obj: $tType).
thf(obj_rel, type, obj_rel: (obj > (obj > $o))).
thf(obj_rel_sym, axiom, (! [RX:obj,RY:obj]: ((((obj_rel @ RX) @ RY) = ((obj_rel @ RY) @ RX))))).
thf(obj_rel_trans, axiom, (! [RX:obj,RY:obj,RZ:obj]: ((((obj_rel @ RX) @ RY) => (((obj_rel @ RY) @ RZ) => ((obj_rel @ RX) @ RZ)))))).
thf(obj_rel_reduce, axiom, (! [RX:obj,RY:obj]: ((((obj_rel @ RY) @ RY) => (((obj_rel @ RX) @ RY) = (RX = RY)))))).
thf(mor_type, type, mor: $tType).
thf(mor_rel, type, mor_rel: (obj > (obj > (mor > (mor > $o))))).
thf(mor_rel_sym, axiom, (! [X:obj,Y:obj]: ((! [RX:mor,RY:mor]: ((((((mor_rel @ X) @ Y) @ RX) @ RY) = ((((mor_rel @ X) @ Y) @ RY) @ RX))))))).
thf(mor_rel_trans, axiom, (! [X:obj,Y:obj]: ((! [RX:mor,RY:mor,RZ:mor]: ((((((mor_rel @ X) @ Y) @ RX) @ RY) => (((((mor_rel @ X) @ Y) @ RY) @ RZ) => ((((mor_rel @ X) @ Y) @ RX) @ RZ)))))))).
thf(mor_rel_reduce, axiom, (! [X:obj,Y:obj]: ((! [RX:mor,RY:mor]: ((((((mor_rel @ X) @ Y) @ RY) @ RY) => (((((mor_rel @ X) @ Y) @ RX) @ RY) = (RX = RY)))))))).
thf(id_type, type, id: (obj > mor)).
thf(id_tp_ax, axiom, (! [X:obj,X_prime:obj]: ((((obj_rel @ X) @ X_prime) => ((((mor_rel @ X) @ X) @ (id @ X)) @ (id @ X)))))).
thf(comp_type, type, comp: (obj > (obj > (obj > (mor > (mor > mor)))))).
thf(comp_tp_ax, axiom, (! [X:obj,X_prime:obj]: ((((obj_rel @ X) @ X_prime) => (! [Y:obj,Y_prime:obj]: ((((obj_rel @ Y) @ Y_prime) => (! [Z:obj,Z_prime:obj]: ((((obj_rel @ Z) @ Z_prime) => (! [F:mor,F_prime:mor]: ((((((mor_rel @ X) @ Y) @ F) @ F_prime) => (! [G:mor,G_prime:mor]: ((((((mor_rel @ Y) @ Z) @ G) @ G_prime) => ((((mor_rel @ X) @ Z) @ (((((comp @ X) @ Y) @ Z) @ F) @ G)) @ (((((comp @ X) @ Y) @ Z) @ F) @ G)))))))))))))))))).
thf(ax1, axiom, (! [X:obj,Y:obj,M:mor]: ((((obj_rel @ X) @ X) => (((obj_rel @ Y) @ Y) => (((((mor_rel @ X) @ Y) @ M) @ M) => ((((mor_rel @ Y) @ X) @ (((((comp @ X) @ X) @ Y) @ (id @ X)) @ M)) @ M))))))).
thf(ax2, axiom, (! [X:obj,Y:obj,M:mor]: ((((obj_rel @ X) @ X) => (((obj_rel @ Y) @ Y) => (((((mor_rel @ X) @ Y) @ M) @ M) => ((((mor_rel @ Y) @ X) @ (((((comp @ X) @ Y) @ Y) @ M) @ (id @ Y))) @ M))))))).
thf(ax3, axiom, (! [X:obj,Y:obj,Z:obj,A:obj,F:mor,G:mor,H:mor]: ((((obj_rel @ X) @ X) => (((obj_rel @ Y) @ Y) => (((obj_rel @ Z) @ Z) => (((obj_rel @ A) @ A) => (((((mor_rel @ X) @ Y) @ F) @ F) => (((((mor_rel @ Y) @ Z) @ G) @ G) => (((((mor_rel @ Z) @ A) @ H) @ H) => ((((mor_rel @ A) @ X) @ (((((comp @ X) @ Y) @ A) @ F) @ (((((comp @ Y) @ Z) @ A) @ G) @ H))) @ (((((comp @ X) @ Z) @ A) @ (((((comp @ X) @ Y) @ Z) @ F) @ G)) @ H)))))))))))).
thf(conj1, conjecture, (! [X:obj,Y:obj]: ((((obj_rel @ X) @ X) => (((obj_rel @ Y) @ Y) => (((obj_rel @ X) @ Y) => ((((mor_rel @ X) @ X) @ (id @ X)) @ (id @ Y)))))))).
%%% thf(conj2, conjecture, (! [X:obj,Y:obj,Z:obj,F:mor,G:mor]: ((((obj_rel @ X) @ X) => (((obj_rel @ Y) @ Y) => (((obj_rel @ Z) @ Z) => (((((mor_rel @ X) @ Y) @ F) @ F) => (((((mor_rel @ Y) @ Z) @ G) @ G) => ((((obj_rel @ X) @ Y) & (((obj_rel @ Y) @ Z) & (((((mor_rel @ X) @ Y) @ F) @ (id @ X)) & ((((mor_rel @ Y) @ Z) @ G) @ (id @ Y))))) => ((((mor_rel @ Z) @ X) @ (((((comp @ X) @ Y) @ Z) @ F) @ G)) @ (id @ Z))))))))))).
%%% thf(conj3, conjecture, (! [X:obj,Y:obj,Z:obj,F:mor,G:mor]: ((((obj_rel @ X) @ X) => (((obj_rel @ Y) @ Y) => (((obj_rel @ Z) @ Z) => (((((mor_rel @ X) @ Y) @ F) @ F) => (((((mor_rel @ Y) @ X) @ G) @ G) => ((((((mor_rel @ X) @ X) @ (((((comp @ X) @ Y) @ X) @ F) @ G)) @ (id @ X)) & ((((mor_rel @ Y) @ Y) @ (((((comp @ Y) @ X) @ Y) @ G) @ F)) @ (id @ Y))) => (! [H:mor]: ((((((mor_rel @ X) @ Z) @ H) @ H) => ((((mor_rel @ Z) @ X) @ (((((comp @ X) @ Y) @ Z) @ F) @ (((((comp @ Y) @ X) @ Z) @ G) @ H))) @ H))))))))))))).
%%% thf(conj4, conjecture, (! [X:obj,Y:obj,Z:obj,F:mor,G:mor]: ((((obj_rel @ X) @ X) => (((obj_rel @ Y) @ Y) => (((obj_rel @ Z) @ Z) => (((((mor_rel @ X) @ Y) @ F) @ F) => (((((mor_rel @ Y) @ X) @ G) @ G) => ((((((mor_rel @ X) @ X) @ (((((comp @ X) @ Y) @ X) @ F) @ G)) @ (id @ X)) & ((((mor_rel @ Y) @ Y) @ (((((comp @ Y) @ X) @ Y) @ G) @ F)) @ (id @ Y))) => (! [H:mor]: ((((((mor_rel @ X) @ Z) @ H) @ H) => ((((mor_rel @ Z) @ X) @ (((((comp @ X) @ Y) @ Z) @ F) @ (((((comp @ Y) @ X) @ Z) @ G) @ H))) @ (((((comp @ X) @ X) @ Z) @ (((((comp @ X) @ Y) @ X) @ F) @ G)) @ H)))))))))))))).
%%% thf(conj5, conjecture, (! [X:obj,Y:obj,Z:obj,F:mor,G:mor,H:mor,J:mor]: ((((obj_rel @ X) @ X) => (((obj_rel @ Y) @ Y) => (((obj_rel @ Z) @ Z) => (((((mor_rel @ X) @ Y) @ F) @ F) => (((((mor_rel @ Y) @ X) @ G) @ G) => (((((mor_rel @ Y) @ Z) @ H) @ H) => (((((mor_rel @ Z) @ Y) @ J) @ J) => ((((((mor_rel @ X) @ X) @ (((((comp @ X) @ Y) @ X) @ F) @ G)) @ (id @ X)) & ((((mor_rel @ Y) @ Y) @ (((((comp @ Y) @ X) @ Y) @ G) @ F)) @ (id @ Y))) => ((((((mor_rel @ Y) @ Y) @ (((((comp @ Y) @ Z) @ Y) @ H) @ J)) @ (id @ Y)) & ((((mor_rel @ Z) @ Z) @ (((((comp @ Z) @ Y) @ Z) @ J) @ H)) @ (id @ Z))) => (! [K:mor]: ((((((mor_rel @ X) @ Z) @ K) @ K) => ((((mor_rel @ Z) @ X) @ (((((comp @ X) @ Z) @ Z) @ (((((comp @ X) @ Y) @ Z) @ F) @ (((((comp @ Y) @ Z) @ Z) @ H) @ (id @ Z)))) @ (((((comp @ Z) @ X) @ Z) @ (((((comp @ Z) @ Y) @ X) @ J) @ G)) @ K))) @ K)))))))))))))))).
