thf(set_type, type, t_set: $tType).
thf(set_rel, type, set_rel: (t_set > (t_set > $o))).
thf(set_per_ax, axiom, (! [V_X:t_set]: ((! [V_X_PRIME:t_set]: ((((set_rel @ V_X) @ V_X_PRIME) => (V_X = V_X_PRIME))))))).
thf(functType_type, type, t_functType: (t_set > (t_set > t_set))).
thf(functType_tp_ax, axiom, (! [V_A:t_set,V_A_PRIME:t_set]: ((((set_rel @ V_A) @ V_A_PRIME) => (! [V_B:t_set,V_B_PRIME:t_set]: ((((set_rel @ V_B) @ V_B_PRIME) => ((set_rel @ ((t_functType @ V_A) @ V_B)) @ ((t_functType @ V_A_PRIME) @ V_B_PRIME))))))))).
thf(funcAppl_type, type, t_funcAppl: (t_set > (t_set > (t_set > (t_set > t_set))))).
thf(funcAppl_tp_ax, axiom, (! [V_A:t_set,V_A_PRIME:t_set]: ((((set_rel @ V_A) @ V_A_PRIME) => (! [V_B:t_set,V_B_PRIME:t_set]: ((((set_rel @ V_B) @ V_B_PRIME) => (! [V_F:t_set,V_F_PRIME:t_set]: ((((set_rel @ V_F) @ V_F_PRIME) => (! [V_X:t_set,V_X_PRIME:t_set]: ((((set_rel @ V_X) @ V_X_PRIME) => ((set_rel @ ((((t_funcAppl @ V_A) @ V_B) @ V_F) @ V_X)) @ ((((t_funcAppl @ V_A_PRIME) @ V_B_PRIME) @ V_F_PRIME) @ V_X_PRIME))))))))))))))).
thf(functionHood_ax, axiom, (! [V_A:t_set]: ((((set_rel @ V_A) @ V_A) => (! [V_B:t_set]: ((((set_rel @ V_B) @ V_B) => (! [V_F:t_set]: ((((set_rel @ V_F) @ V_F) => (! [V_X:t_set]: ((((set_rel @ V_X) @ V_X) => (! [V_Y:t_set]: ((((set_rel @ V_Y) @ V_Y) => (((set_rel @ V_X) @ V_Y) => ((set_rel @ t_funcAppl(V_A,V_B,V_F,V_X)) @ t_funcAppl(V_A,V_B,V_F,V_Y))))))))))))))))))).
thf(functExt_ax, axiom, (! [V_A:t_set]: ((((set_rel @ V_A) @ V_A) => (! [V_B:t_set]: ((((set_rel @ V_B) @ V_B) => (! [V_F:t_set]: ((((set_rel @ V_F) @ V_F) => (! [V_G:t_set]: ((((set_rel @ V_G) @ V_G) => ((! [V_X:t_set]: ((((set_rel @ V_X) @ V_X) => ((set_rel @ t_funcAppl(V_A,V_B,V_F,V_X)) @ t_funcAppl(V_A,V_B,V_G,V_X))))) => ((set_rel @ V_F) @ V_G))))))))))))))).
thf(concat_type, type, t_concat: (t_set > (t_set > (t_set > (t_set > (t_set > t_set)))))).
thf(concat_tp_ax, axiom, (! [V_A:t_set,V_A_PRIME:t_set]: ((((set_rel @ V_A) @ V_A_PRIME) => (! [V_B:t_set,V_B_PRIME:t_set]: ((((set_rel @ V_B) @ V_B_PRIME) => (! [V_C:t_set,V_C_PRIME:t_set]: ((((set_rel @ V_C) @ V_C_PRIME) => (! [V_F:t_set,V_F_PRIME:t_set]: ((((set_rel @ V_F) @ V_F_PRIME) => (! [V_G:t_set,V_G_PRIME:t_set]: ((((set_rel @ V_G) @ V_G_PRIME) => ((set_rel @ (((((t_concat @ V_A) @ V_B) @ V_C) @ V_F) @ V_G)) @ (((((t_concat @ V_A_PRIME) @ V_B_PRIME) @ V_C_PRIME) @ V_F_PRIME) @ V_G_PRIME)))))))))))))))))).
thf(concatAppl_ax, axiom, (! [V_A:t_set]: ((((set_rel @ V_A) @ V_A) => (! [V_B:t_set]: ((((set_rel @ V_B) @ V_B) => (! [V_C:t_set]: ((((set_rel @ V_C) @ V_C) => (! [V_F:t_set]: ((((set_rel @ V_F) @ V_F) => (! [V_G:t_set]: ((((set_rel @ V_G) @ V_G) => (! [V_X:t_set]: ((((set_rel @ V_X) @ V_X) => ((set_rel @ t_funcAppl(V_A,V_C,t_concat(V_A,V_B,V_C,V_F,V_G),V_X)) @ t_funcAppl(V_B,V_C,V_F,t_funcAppl(V_A,V_B,V_G,V_X)))))))))))))))))))))).
thf(conjecture, conjecture, (! [V_A:t_set]: ((((set_rel @ V_A) @ V_A) => (! [V_B:t_set]: ((((set_rel @ V_B) @ V_B) => (! [V_C:t_set]: ((((set_rel @ V_C) @ V_C) => (! [V_D:t_set]: ((((set_rel @ V_D) @ V_D) => (! [V_F:t_set]: ((((set_rel @ V_F) @ V_F) => (! [V_G:t_set]: ((((set_rel @ V_G) @ V_G) => (! [V_H:t_set]: ((((set_rel @ V_H) @ V_H) => ((set_rel @ t_concat(V_A,V_C,V_D,V_F,t_concat(V_A,V_B,V_C,V_G,V_H))) @ t_concat(V_A,V_B,V_D,t_concat(V_B,V_C,V_D,V_F,V_G),V_H)))))))))))))))))))))))).